# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SmartCase' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SmartCase

      pod 'SVProgressHUD'
      pod 'IQKeyboardManagerSwift', '~> 6.0.1'
      pod 'MBProgressHUD'
      pod 'TOPasscodeViewController', :git => "https://github.com/TimOliver/TOPasscodeViewController", :branch => "master"

  target 'SmartCaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SmartCaseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
